version: '3.5'

services:
  db:
    image: mysql:5.7
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes: ["./:/var/www/html"]
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpres
      WORDPRESS_DB_NAME: wordpress
  cli:
    depends_on:
      - db
    image: wordpress:cli
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    command: sh -c "sleep 20 && wp config create --force --dbname=$$WORDPRESS_DB_NAME --dbuser=$$WORDPRESS_DB_USER --dbpass=$$WORDPRESS_DB_PASSWORD --dbhost=$$WORDPRESS_DB_HOST && wp core install --path=/var/www/html --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=test@example.com; wp core update"

volumes:
  wp_db_data:
